version: '3'
services:
  db:
    image: mysql
    container_name: challengedb
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: mysql --user=$$MYSQL_ROOT_USER --password=$$MYSQL_ROOT_PASSWORD -e 'SHOW DATABASES;'
      interval: 5s
      timeout: 20s
      retries: 10
  app:
    restart: on-failure
    image: challengeapp
    container_name: challengeapp
    ports:
      - '5000:80'
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
